# Generated by Django 5.2.6 on 2026-06-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanguarantor',
            options={'ordering': ['loan', 'guarantor']},
        ),
    ]
