# Generated by Django 5.2.6 on 2026-06-04 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_loanguarantor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
