# Generated by Django 5.2.6 on 2026-06-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_loan_outstanding_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("login", "Login"), ("logout", "Logout"), ("login_failed", "Failed Login"), ("create", "Create"), ("update", "Update"), ("delete", "Delete"), ("workflow", "Workflow"), ("denied", "Access Denied")], max_length=30)),
                ("module", models.CharField(blank=True, max_length=80)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="core_activi_user_id_599332_idx"),
                    models.Index(fields=["action", "created_at"], name="core_activi_action_4055cf_idx"),
                    models.Index(fields=["module", "created_at"], name="core_activi_module_66734e_idx"),
                ],
            },
        ),
    ]
