# Generated by Django 5.2.6 on 2026-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_member_gender_alter_member_member_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_no',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
